<a href="https://colab.research.google.com/github/ReemAlazmi28/python-data-science-portfolio/blob/main/03_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas

series
we use it to stor a any data type( int, flout , string,....)
it has index and values each index point to a serten value

In [2]:
import pandas as pd

In [3]:
lst = [1,2,3,4]
s = pd.Series(lst)
s
#the first column has the index and the second has the value

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
#changing the series data type
lst = [1,2,3,4]
s = pd.Series(lst, dtype= float)
s

0    1.0
1    2.0
2    3.0
3    4.0
dtype: float64

In [5]:
#chang the index
lst = [1,2,3,4]
s = pd.Series(lst, dtype= float, index =['A','B','C','D'])
s

A    1.0
B    2.0
C    3.0
D    4.0
dtype: float64

### concat()

In [6]:
#merging the series
x = pd.Series(['Reem','Layla'])
y = pd.Series(['Mona','Dina'])

z=pd.concat([x,y]) # this function merge both
z

0     Reem
1    Layla
0     Mona
1     Dina
dtype: object

In [7]:
x = pd.Series(['Reem','Layla'])
y = pd.Series(['Mona','Dina'])

z=pd.concat([x,y], ignore_index = True) # this function merge both & change the index from 0 to 3
z

0     Reem
1    Layla
2     Mona
3     Dina
dtype: object

### Delete element from the series / drop()

In [8]:
s = pd.Series({10:'A', 20:'B',30:'C',40:'D',50:'B'}) # creat serise
s

10    A
20    B
30    C
40    D
50    B
dtype: object

In [9]:
s.drop(30) #delet but not permantly

10    A
20    B
40    D
50    B
dtype: object

In [10]:
s # print agane (nit deleted)

10    A
20    B
30    C
40    D
50    B
dtype: object

In [11]:
# first way
z= s.drop(30)  # delet and save in new varible
z

10    A
20    B
40    D
50    B
dtype: object

In [12]:
#second way
s = pd.Series({10:'A', 20:'B',30:'C',40:'D',50:'B'})
s.drop(30, inplace = True) # delet the one we want the save in s
s

10    A
20    B
40    D
50    B
dtype: object

### ()drop_duplicates
#### delet the repeted values

In [13]:
s = pd.Series({10:'A', 20:'B',30:'C',40:'D',50:'B'}) # creat serise
s

10    A
20    B
30    C
40    D
50    B
dtype: object

In [14]:
s.drop_duplicates() # delet repeted values

10    A
20    B
30    C
40    D
dtype: object

In [15]:
s.drop_duplicates(inplace=True) # save after deletion

In [16]:
s

10    A
20    B
30    C
40    D
dtype: object

 ### ()Copy

In [17]:
s=pd.Series([1,2,3])
s2 = s.copy()

In [18]:
s2

0    1
1    2
2    3
dtype: int64

In [19]:
s2.drop(0,inplace = True)
s2

1    2
2    3
dtype: int64

In [20]:
s

0    1
1    2
2    3
dtype: int64

### add()
### sub()
### mul()
### div()

In [21]:
s = pd.Series([1,2,3,4,5])

In [22]:
s = s.add(5) #add5 for each value
s

0     6
1     7
2     8
3     9
4    10
dtype: int64

In [23]:
s = s.sub(5)
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [24]:
s = s.mul(-1)
s

0   -1
1   -2
2   -3
3   -4
4   -5
dtype: int64

In [25]:
s= s.div(2)
s

0   -0.5
1   -1.0
2   -1.5
3   -2.0
4   -2.5
dtype: float64

# DataFrame
#### A table of data with rows and columns (the first column is the index)

In [ ]:
data = {
    'StudentName' :['Reem','Nada','Majd','Nawaf'],
    'StudntGrade':['A+','A','B','B+']
}
Students = pd.DataFrame(data)
Students

  StudentName StudntGrade
0        Reem          A+
1        Nada           A
2        Majd           B
3       Nawaf          B+

In [ ]:
import pandas as pd
# Replace with your actual file path
Students = pd.read_csv('Students.csv')
Students

          Name Major  Level   GPA
0         Reem    CS      7  4.40
1         Nada    IT      1  4.80
2         Sara    IS      1  3.45
3         Majd    IT      4  4.71
4    Student_1    CS      6  4.00
5      Alanoud    CS      9  4.88
6         Amal    IT      5  4.99
7         Yara    IS      8  4.50
8        Nawaf    CS      2  3.33
9        Fahad    IT      1  3.75
10        Dana    IS      8  4.10
11        Lama    CS      4  3.90
12        Omar    IT      4  3.60
13       Aisha    IS      8  4.20
14       Tariq    CS      2  4.00
15        Noor    CS      9  4.30
16  Student_17    IS      5  4.10
17  Student_18    IS      8  4.20
18  Student_19    IS      1  4.30
19  Student_20    IS      7  4.40
20  Student_21    IS      1  3.50
21  Student_22    IS      2  3.60
22  Student_23    IS      6  3.70

### head() & tail() Functions

In [ ]:
# show the first 5 lines from the data fram
Students.head(5)

        Name Major  Level   GPA
0       Reem    CS      7  4.40
1       Nada    IT      1  4.80
2       Sara    IS      1  3.45
3       Majd    IT      4  4.71
4  Student_1    CS      6  4.00

In [ ]:
# show the last 3 lines
Students.tail(3)

          Name Major  Level  GPA
20  Student_21    IS      1  3.5
21  Student_22    IS      2  3.6
22  Student_23    IS      6  3.7

### groupby()
#### Groups rows by a column and applies aggregate functions (e.g. mean, sum)

In [ ]:
Students[['Major','GPA']].groupby('Major').mean() #ابي اعرض التخصص و المعدل و اجمع الطلاب اللي تخصصاتهم مشابها في قروب بروح و ابي اطلع الافرج حق هذول الطلاب اللي من تخصص معين

            GPA
Major
CS     4.115714
IS     4.004545
IT     4.370000

In [ ]:
Students[['Level','GPA']].groupby('Level').mean()

            GPA
Level
1      3.960000
2      3.643333
4      4.070000
5      4.545000
6      3.850000
7      4.400000
8      4.250000
9      4.590000

In [ ]:
Students.describe() # this function will give us a statistic info onout the dtat frame

           Level        GPA
count  23.000000  23.000000
mean    4.739130   4.117826
std     2.911067   0.472575
min     1.000000   3.330000
25%     2.000000   3.725000
50%     5.000000   4.100000
75%     7.500000   4.400000
max     9.000000   4.990000

In [ ]:
Students.describe(include=[object])

        Name Major
count     23    23
unique    23     3
top     Reem    IS
freq       1    11

In [ ]:
Students.sample() # return random data row

          Name Major  Level  GPA
16  Student_17    IS      5  4.1

# reaching data in specific COLUMN

In [ ]:
Students[['Name']] # one column

          Name
0         Reem
1         Nada
2         Sara
3         Majd
4    Student_1
5      Alanoud
6         Amal
7         Yara
8        Nawaf
9        Fahad
10        Dana
11        Lama
12        Omar
13       Aisha
14       Tariq
15        Noor
16  Student_17
17  Student_18
18  Student_19
19  Student_20
20  Student_21
21  Student_22
22  Student_23

In [ ]:
Students[['Name','Major']]

          Name Major
0         Reem    CS
1         Nada    IT
2         Sara    IS
3         Majd    IT
4    Student_1    CS
5      Alanoud    CS
6         Amal    IT
7         Yara    IS
8        Nawaf    CS
9        Fahad    IT
10        Dana    IS
11        Lama    CS
12        Omar    IT
13       Aisha    IS
14       Tariq    CS
15        Noor    CS
16  Student_17    IS
17  Student_18    IS
18  Student_19    IS
19  Student_20    IS
20  Student_21    IS
21  Student_22    IS
22  Student_23    IS

# reaching data in specific ROW

In [ ]:
Students[3:7] # show from index 3 to index 6

        Name Major  Level   GPA
3       Majd    IT      4  4.71
4  Student_1    CS      6  4.00
5    Alanoud    CS      9  4.88
6       Amal    IT      5  4.99

In [ ]:
Students.loc[1:5 , ['Name','Major']] # return the indecs fron 1 to 5 and only show the name and the  major column

        Name Major
1       Nada    IT
2       Sara    IS
3       Majd    IT
4  Student_1    CS
5    Alanoud    CS

In [ ]:
Students.sample(5 , random_state=23) # give us 5  random data and make them stop changing

          Name Major  Level  GPA
18  Student_19    IS      1  4.3
14       Tariq    CS      2  4.0
16  Student_17    IS      5  4.1
4    Student_1    CS      6  4.0
0         Reem    CS      7  4.4

# show a data by a condition

In [ ]:
Students[Students['GPA']>4.50]

      Name Major  Level   GPA
1     Nada    IT      1  4.80
3     Majd    IT      4  4.71
5  Alanoud    CS      9  4.88
6     Amal    IT      5  4.99

In [ ]:
Students.isnull()

     Name  Major  Level    GPA
0   False  False  False  False
1   False  False  False  False
2   False  False  False  False
3   False  False  False  False
4   False  False  False  False
5   False  False  False  False
6   False  False  False  False
7   False  False  False  False
8   False  False  False  False
9   False  False  False  False
10  False  False  False  False
11  False  False  False  False
12  False  False  False  False
13  False  False  False  False
14  False  False  False  False
15  False  False  False  False
16  False  False  False  False
17  False  False  False  False
18  False  False  False  False
19  False  False  False  False
20  False  False  False  False
21  False  False  False  False
22  False  False  False  False

In [ ]:
Students[Students['Level'].isnull()] # filtering the null values

Empty DataFrame
Columns: [Name, Major, Level, GPA]
Index: []

In [ ]:
Students[Students["Name"] == "Reem"] # show reem data fram

   Name Major  Level  GPA
0  Reem    CS      7  4.4

In [ ]:
Students[Students["Major"] == "CS"] # show all the students with CS major

         Name Major  Level   GPA
0        Reem    CS      7  4.40
4   Student_1    CS      6  4.00
5     Alanoud    CS      9  4.88
8       Nawaf    CS      2  3.33
11       Lama    CS      4  3.90
14      Tariq    CS      2  4.00
15       Noor    CS      9  4.30

# Data manipulating

In [ ]:
Students['Level'].max() # return the largest value in level column

9

In [ ]:
Students['Level'].min() # return the smalest value in level column

1

In [ ]:
Students['Level'].sum() # return the sum of all the values in level column

109

## apply() function

In [ ]:
def gpaBonus(gpa):
    gpa = gpa+0.15
    return gpa

In [ ]:
Students['GPA'] = Students['GPA'].apply(gpaBonus) # To save the changes Stusents['GPA'] , to apply a function use apply(function name)

In [ ]:
Students

          Name Major  Level   GPA
0         Reem    CS      7  4.55
1         Nada    IT      1  4.95
2         Sara    IS      1  3.60
3         Majd    IT      4  4.86
4    Student_1    CS      6  4.15
5      Alanoud    CS      9  5.03
6         Amal    IT      5  5.14
7         Yara    IS      8  4.65
8        Nawaf    CS      2  3.48
9        Fahad    IT      1  3.90
10        Dana    IS      8  4.25
11        Lama    CS      4  4.05
12        Omar    IT      4  3.75
13       Aisha    IS      8  4.35
14       Tariq    CS      2  4.15
15        Noor    CS      9  4.45
16  Student_17    IS      5  4.25
17  Student_18    IS      8  4.35
18  Student_19    IS      1  4.45
19  Student_20    IS      7  4.55
20  Student_21    IS      1  3.65
21  Student_22    IS      2  3.75
22  Student_23    IS      6  3.85

## drop() Function

In [ ]:
import pandas as pd
# Replace with your actual file path
Students = pd.read_csv('Students.csv')
Students

          Name Major  Level   GPA
0         Reem    CS      7  4.40
1         Nada    IT      1  4.80
2         Sara    IS      1  3.45
3         Majd    IT      4  4.71
4    Student_1    CS      6  4.00
5      Alanoud    CS      9  4.88
6         Amal    IT      5  4.99
7         Yara    IS      8  4.50
8        Nawaf    CS      2  3.33
9        Fahad    IT      1  3.75
10        Dana    IS      8  4.10
11        Lama    CS      4  3.90
12        Omar    IT      4  3.60
13       Aisha    IS      8  4.20
14       Tariq    CS      2  4.00
15        Noor    CS      9  4.30
16  Student_17    IS      5  4.10
17  Student_18    IS      8  4.20
18  Student_19    IS      1  4.30
19  Student_20    IS      7  4.40
20  Student_21    IS      1  3.50
21  Student_22    IS      2  3.60
22  Student_23    IS      6  3.70

In [ ]:
Students.drop('Name', axis = 1 , inplace= True) # axis = 0 (row) axis =1 (column) # Remove the column name

In [ ]:
Students

   Major  Level   GPA
0     CS      7  4.40
1     IT      1  4.80
2     IS      1  3.45
3     IT      4  4.71
4     CS      6  4.00
5     CS      9  4.88
6     IT      5  4.99
7     IS      8  4.50
8     CS      2  3.33
9     IT      1  3.75
10    IS      8  4.10
11    CS      4  3.90
12    IT      4  3.60
13    IS      8  4.20
14    CS      2  4.00
15    CS      9  4.30
16    IS      5  4.10
17    IS      8  4.20
18    IS      1  4.30
19    IS      7  4.40
20    IS      1  3.50
21    IS      2  3.60
22    IS      6  3.70

In [ ]:
Students.drop(5,axis=0 ,inplace=True ) # delet the 5th row

In [ ]:
Students

   Major  Level   GPA
0     CS      7  4.40
1     IT      1  4.80
2     IS      1  3.45
3     IT      4  4.71
4     CS      6  4.00
6     IT      5  4.99
7     IS      8  4.50
8     CS      2  3.33
9     IT      1  3.75
10    IS      8  4.10
11    CS      4  3.90
12    IT      4  3.60
13    IS      8  4.20
14    CS      2  4.00
15    CS      9  4.30
16    IS      5  4.10
17    IS      8  4.20
18    IS      1  4.30
19    IS      7  4.40
20    IS      1  3.50
21    IS      2  3.60
22    IS      6  3.70

# dropna() Function
### to delet the null values

In [ ]:
Students.dropna(how="all", axis=0) # if all the row is = to null value
# Students.dropna(how="any", axis=0) #delet any row that has null value not nessecry all of the row

   Major  Level   GPA
0     CS      7  4.40
1     IT      1  4.80
2     IS      1  3.45
3     IT      4  4.71
4     CS      6  4.00
6     IT      5  4.99
7     IS      8  4.50
8     CS      2  3.33
9     IT      1  3.75
10    IS      8  4.10
11    CS      4  3.90
12    IT      4  3.60
13    IS      8  4.20
14    CS      2  4.00
15    CS      9  4.30
16    IS      5  4.10
17    IS      8  4.20
18    IS      1  4.30
19    IS      7  4.40
20    IS      1  3.50
21    IS      2  3.60
22    IS      6  3.70

In [ ]:
Students.dropna(how="any", axis=1) # delet any column that hase nul value

## fillna()
#### Replaces null values with a specified value

# Sorting

In [ ]:
Students.sort_values(by='GPA', ascending =False , inplace = True ) # sort from largest to smallest

In [ ]:
Students

   Major  Level   GPA
6     IT      5  4.99
1     IT      1  4.80
3     IT      4  4.71
7     IS      8  4.50
0     CS      7  4.40
19    IS      7  4.40
18    IS      1  4.30
15    CS      9  4.30
17    IS      8  4.20
13    IS      8  4.20
16    IS      5  4.10
10    IS      8  4.10
4     CS      6  4.00
14    CS      2  4.00
11    CS      4  3.90
9     IT      1  3.75
22    IS      6  3.70
21    IS      2  3.60
12    IT      4  3.60
20    IS      1  3.50
2     IS      1  3.45
8     CS      2  3.33

In [ ]:
Students.sort_index(axis=0 ,ascending= False , inplace = True) # sort the index decresing

In [ ]:
Students

   Major  Level   GPA
22    IS      6  3.70
21    IS      2  3.60
20    IS      1  3.50
19    IS      7  4.40
18    IS      1  4.30
17    IS      8  4.20
16    IS      5  4.10
15    CS      9  4.30
14    CS      2  4.00
13    IS      8  4.20
12    IT      4  3.60
11    CS      4  3.90
10    IS      8  4.10
9     IT      1  3.75
8     CS      2  3.33
7     IS      8  4.50
6     IT      5  4.99
4     CS      6  4.00
3     IT      4  4.71
2     IS      1  3.45
1     IT      1  4.80
0     CS      7  4.40

# groupby()

In [ ]:
Students[['Major','GPA']].groupby("Major").mean()

            GPA
Major
CS     3.988333
IS     4.004545
IT     4.370000